## Accessing list elements using index values

In [15]:
import numpy as np

In [16]:
lst1=[10,20,30,40,50]

In [17]:
lst2=[[10,20,30,40],[50,60,70,80],[90,18,21,11]]

In [18]:
lst1[1]

20

In [19]:
lst2[1][1]

60

In [20]:
# lst2[1,1]
# TypeError: list indices must be integers or slices, not tuple

In [21]:
arr1=np.array(lst1)
arr1

array([10, 20, 30, 40, 50])

In [22]:
arr2=np.array(lst2)
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [90, 18, 21, 11]])

- arr[ row , col ]
- arrays can accept the multi index.

In [25]:
arr1[2]

30

In [24]:
arr2[1,1]

60

In [26]:
arr2[1][3]

80

## Slicing method in arrays
- arr[start : stop : step]

In [35]:
lst1[::-1]

[50, 40, 30, 20, 10]

In [33]:
lst2[::-1]
# it reverse only the outer elemens not the inner elements

[[90, 18, 21, 11], [50, 60, 70, 80], [10, 20, 30, 40]]

In [49]:
lst2[::-1]

[[90, 18, 21, 11], [50, 60, 70, 80], [10, 20, 30, 40]]

In [50]:
arr2[::, ::-1]

array([[40, 30, 20, 10],
       [80, 70, 60, 50],
       [11, 21, 18, 90]])

In [51]:
arr2[::-1,::-1]

array([[11, 21, 18, 90],
       [80, 70, 60, 50],
       [40, 30, 20, 10]])