In [1]:
import numpy as np

In [2]:
l1=[1,2,3,]
a1=np.array(l1)
a1

array([1, 2, 3])

In [3]:
l2=[6,7,8]
a2=np.array(l2)
a2

array([6, 7, 8])

## Arithematic operations

In [4]:
print(a1+a2)
# adds the corresponding elements inside the array.

[ 7  9 11]


In [5]:
print(a1-a2)
print(a1*a2)
print(a1**a2)
print(a1/a2)
print(a1%a2)
print(a1//a2)

[-5 -5 -5]
[ 6 14 24]
[   1  128 6561]
[0.16666667 0.28571429 0.375     ]
[1 2 3]
[0 0 0]


## Comparison operators

In [6]:
print(a1==a2)
print(a1!=a2)
print(a1<a2)
print(a1<=a2)
print(a1>a2)
print(a1>=a2)

[False False False]
[ True  True  True]
[ True  True  True]
[ True  True  True]
[False False False]
[False False False]


In [7]:
print((a1>5).all() and (a1<10).any())

False


In [8]:
print((a2>5).any() and (a2<10).any())

True
