In [1]:
import numpy as np

In [3]:
a1=np.array([[1,2,3],[10,20,30]])
print(a1)

[[ 1  2  3]
 [10 20 30]]


In [4]:
np.reshape(a1,(-1))

array([ 1,  2,  3, 10, 20, 30])

## ravel( )
- it also converts any shape of array into 1D array.
- it behaves like a view, it is dependent, when we change the value in updated array its also making the changes original array due to common memory location.

In [8]:
x=a1.ravel()
# print(x)

x[0]=50
print(a1,x,sep='\n')

[[50  2  3]
 [10 20 30]]
[50  2  3 10 20 30]


In [10]:
a4=np.array([[11,22,33],[4,67,80]])
print(a4)

[[11 22 33]
 [ 4 67 80]]


## flatten( )
- it also behaves like a reshape, it also converts any shape of array to 1A array
- it is independent

In [12]:
y=a4.flatten()
print(y)

y[-1]=90
print(a4,y,sep='\n')

[11 22 33  4 67 80]
[[11 22 33]
 [ 4 67 80]]
[11 22 33  4 67 90]
