In [1]:
import numpy as np

In [3]:
a1=np.array([10,20,30])
print(a1)

[10 20 30]


## shallow copy

In [8]:
s_a=np.copy(a1)
print(s_a)

s_a[0]=100
print(s_a)
print(a1)

[10 20 30]
[100  20  30]
[10 20 30]
