In [1]:
import numpy as np

In [2]:
a1=np.array([10,20,30,])
print(a1)

[10 20 30]


- power( ) function
- for each element in the array it will multiply the value itself, based on the power value given

In [8]:
np.power(a1,2)

array([100, 400, 900], dtype=int32)

- sum( ) function
- sum( ) will add all the elements in the array 

In [9]:
np.sum(a1)

60

- std( ) function gives the standard deviation of the array passed

In [11]:
np.std(a1)

8.16496580927726

- mean( ) gives the average value of given array

In [12]:
np.mean(a1)

20.0

- var( ) function 
- used to check the how far the value is from the mean value
- if variance value is less, near to the mean value
- if variance value is high, far from the mean value

In [13]:
np.var(a1)

66.66666666666667

In [16]:
a2=np.array([1,0,2])
print(a2)

[1 0 2]


- exp( ) function
- gives the power value

In [17]:
np.exp(a2)

array([2.71828183, 1.        , 7.3890561 ])

- log( ) functions
- gives the value of that power

In [19]:
a3=np.array([2.71828183, 1.        , 7.3890561 ])
np.log(a3)

array([1., 0., 2.])