In [2]:
import numpy as np

In [3]:
a1=np.arange(10,96,5)
print(a1)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [4]:
print(a1.shape)

(18,)


-  When we have to reshape an array we have to check with the multiples of the array values length. 
- For eg. 18 is size of the array , we have 18 elements, so multiples of 18 are 2X9, 3X6 etc.

In [7]:
np.reshape(a1, (3,6))

array([[10, 15, 20, 25, 30, 35],
       [40, 45, 50, 55, 60, 65],
       [70, 75, 80, 85, 90, 95]])

In [10]:
a2=np.reshape(a1,(3,2,3))
print(a2)

[[[10 15 20]
  [25 30 35]]

 [[40 45 50]
  [55 60 65]]

 [[70 75 80]
  [85 90 95]]]


- when i pass the reshape size as -1 then it will convert any shape of array to the 1D array.

In [14]:
np.reshape(a2,(-1))

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [22]:
a3=np.array([[10,20,30,40,50,78],[2,4,5,60,64,28],[11,9,37,92,55,68]])
print(a3)
print(a3.shape)
print('Dimension: ',a3.ndim)
print('Size: ', a3.size)

[[10 20 30 40 50 78]
 [ 2  4  5 60 64 28]
 [11  9 37 92 55 68]]
(3, 6)
Dimension:  2
Size:  18


In [26]:
np.reshape(a3,(3,2,1,3))
np.reshape(a3, (3,3,2))

array([[[10, 20],
        [30, 40],
        [50, 78]],

       [[ 2,  4],
        [ 5, 60],
        [64, 28]],

       [[11,  9],
        [37, 92],
        [55, 68]]])