In [1]:
import numpy as np

In [3]:
a1=np.array([10,20,30])
print(a1)

[10 20 30]


## copy( )
- copy is independent

In [8]:
s_a=np.copy(a1)
print(s_a)

s_a[0]=100
print(s_a)
print(a1)

[10 20 30]
[100  20  30]
[10 20 30]


## view( )

- view( ) will also copy the elements, but it points to same memory location.
- view is dependent

In [12]:
a3=a1.view()
print('a3:' ,a3)
print('a1:' ,a1)

a3[-1]=200
print('a3:', a3)
print('a1:',a1)

a3: [10 20 30]
a1: [10 20 30]
a3: [ 10  20 200]
a1: [ 10  20 200]
