In [5]:
import numpy as np

In [6]:
r=range(0,100,2)

In [9]:
a=np.array(r)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

- Here in numpy instead of range( ) we use arange(start,stop,step)

In [12]:
a1=np.arange(0,100,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### linspace( )
- It is going to divide the numbers into differnent equal parts
- By default it will use 50 parts to divide equally
- It includes the stop value also

In [25]:
np.linspace(0,10,5,retstep=True) # retstep returns the step value 
np.linspace(0,10,5,retstep=True,endpoint=False) # if i dont want to include the endvalue then use endpoint=False


(array([0., 2., 4., 6., 8.]), 2.0)

In [ ]:
# for i in np.linspace(0,10,5,endpoint=False):
#     print(i)

0.0
2.0
4.0
6.0
8.0
