In [66]:
import numpy as np

In [67]:
l1=[100,200,300,400,500]
y=[x+50 for x in l1]
y

[150, 250, 350, 450, 550]

In [68]:
a1=np.array(l1)
print(a1)
type(a1)

[100 200 300 400 500]


numpy.ndarray

In [69]:
l2=[10,3.5,'np',9+3j]
np.array(l2)

array(['10', '3.5', 'np', '(9+3j)'], dtype='<U64')

In [70]:
l1=[100,200,300,400,500]
l2=[10,3.5,'np',9+3j]
print(l1+l2)


[100, 200, 300, 400, 500, 10, 3.5, 'np', (9+3j)]


In [71]:
l1=[100,200,300,400,500]
l2=[10,20,30,40,50]
arr1=np.array(l1)
arr2=np.array(l2)
print(arr1+arr2)


[110 220 330 440 550]


In [72]:
arr3=np.array([10,2,5,60,40,80,8,4])
arr3

array([10,  2,  5, 60, 40, 80,  8,  4])

In [73]:
# print(arr2+arr3) #Should of same size
'''ValueError: operands could not be broadcast together with shapes (5,) (8,)'''

'ValueError: operands could not be broadcast together with shapes (5,) (8,)'

In [74]:
arr4=np.array([[10,20],[30,40],[50,60]])

In [75]:
# print(arr1+arr4) #should be of same dimensional
'''ValueError: operands could not be broadcast together with shapes (5,) (3,2)'''

'ValueError: operands could not be broadcast together with shapes (5,) (3,2)'

In [76]:
'''To check the dimension of array'''
arr4.ndim

2

In [77]:
'''To check number of rows and columns'''
arr4.shape

(3, 2)

In [78]:
'''To check the size of the array'''
arr4.size

6

In [79]:
'''To check each item size in bytes'''
arr4.itemsize

4

In [80]:
'''To check the total number of bytes for the array'''
arr4.nbytes

24