In [16]:
import numpy as np

## Broadcasting in arrays
- array rules
- applying one value to each and every element

In [17]:
l1=[10,20,30]
a1=np.array(l1)
print(a1)
a1.shape

[10 20 30]


(3,)

In [20]:
c=100
a1+c

array([110, 120, 130])

In [24]:
l2=[11,12,13]
a2=np.array(l2)
print(a2)
a2.shape

[11 12 13]


(3,)

In [25]:
a1+a2

array([21, 32, 43])

In [29]:
a3=np.array([100,200,300,400])
# a1+a3 ValueError: operands could not be broadcast together with shapes (3,) (4,)

***Rules for broadcasting*** 
- elements must be equal(shape) eg. a1.shape=(3,2) and a2.shape(3,2), always compares from right to left.
- Checks for the rules (2==2, 2==1, 2==empty)
- If all the conditions are true then only it performs operations

In [31]:
a4=np.array([[1,2,3],[5,6,7]])
print(a4)
print(a4.shape)

[[1 2 3]
 [5 6 7]]
(2, 3)


In [32]:
a1+a4

array([[11, 22, 33],
       [15, 26, 37]])