## Accessing list elements using index values

In [61]:
import numpy as np

In [62]:
lst1=[10,20,30,40,50]

In [63]:
lst2=[[10,20,30,40],[50,60,70,80],[90,89,72,11]]

In [64]:
lst1[1]

20

In [65]:
lst2[1][1]

60

In [66]:
# lst2[1,1]
# TypeError: list indices must be integers or slices, not tuple

In [67]:
arr1=np.array(lst1)
arr1

array([10, 20, 30, 40, 50])

In [68]:
arr2=np.array(lst2)
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [90, 89, 72, 11]])

- arr[ row , col ]
- arrays can accept the multi index.

In [69]:
arr1[2]

30

In [70]:
arr2[1,1]

60

In [71]:
arr2[1][3]

80

## Slicing method in arrays
- arr[start : stop : step]

In [72]:
lst1[::-1]

[50, 40, 30, 20, 10]

In [73]:
lst2[::-1]
# it reverse only the outer elemens not the inner elements

[[90, 89, 72, 11], [50, 60, 70, 80], [10, 20, 30, 40]]

In [74]:
lst2[::-1]

[[90, 89, 72, 11], [50, 60, 70, 80], [10, 20, 30, 40]]

In [75]:
arr2[::, ::-1]

array([[40, 30, 20, 10],
       [80, 70, 60, 50],
       [11, 72, 89, 90]])

In [76]:
arr2[::-1]

array([[90, 89, 72, 11],
       [50, 60, 70, 80],
       [10, 20, 30, 40]])

In [77]:
arr2[::-1,2] #it will select the whole column

array([72, 70, 30])

In [78]:
arr2[::-1,::-1]

array([[11, 72, 89, 90],
       [80, 70, 60, 50],
       [40, 30, 20, 10]])

In [79]:
arr2[::-1][2] # it will select the whole row

array([10, 20, 30, 40])

In [80]:
arr2[::2]

array([[10, 20, 30, 40],
       [90, 89, 72, 11]])

In [81]:
arr2[::2,::2]

array([[10, 30],
       [90, 72]])

In [82]:
arr2[:1:,::2]

array([[10, 30]])

In [83]:
lst3=[[[10,20],[30,40]],[[1,2],[50,60]]]

In [86]:
arr3=np.array(lst3)
arr3

array([[[10, 20],
        [30, 40]],

       [[ 1,  2],
        [50, 60]]])

In [93]:
arr3[1,0,1]

2

In [94]:
arr3[::,::,::]

array([[[10, 20],
        [30, 40]],

       [[ 1,  2],
        [50, 60]]])

In [95]:
arr3[::-1,:1:,::2]

array([[[ 1]],

       [[10]]])