In [1]:
import numpy as np

In [2]:
r=range(0,100,2)

In [3]:
a=np.array(r)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

- Here in numpy instead of range( ) we use arange(start,stop,step)

In [4]:
a1=np.arange(0,100,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### linspace( )
- It is going to divide the numbers into differnent equal parts
- By default it will use 50 parts to divide equally
- It includes the stop value also

In [5]:
np.linspace(0,10,5,retstep=True) # retstep returns the step value 
np.linspace(0,10,5,retstep=True,endpoint=False) # if i dont want to include the endvalue then use endpoint=False


(array([0., 2., 4., 6., 8.]), 2.0)

In [6]:
# for i in np.linspace(0,10,5,endpoint=False):
#     print(i)

- Zeros function will create a matrix only containing zeros based on the size passed in zeros( )

In [7]:
np.zeros(2)

array([0., 0.])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

- ones function will a matrix only containing only 1's based on the size passed

In [10]:
np.ones(2)

array([1., 1.])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

- eye method creats a identity matrix i.e it always generates square matrix

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

full(shape, fill_value) - it will a create a matrix of the values passed in fill_value based on the shape 

In [15]:
np.full((3,3),fill_value=3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [16]:
import numpy.random as rd

- randint( ) generates the random integers random numbers within the range which we have mentioned.

In [17]:
rd.randint(2)

1

In [18]:
rd.randint(10,100)

11

In [19]:
rd.randint(10,100,(3))

array([62, 53, 80])

In [20]:
rd.randint(10,100,(3,2))

array([[18, 54],
       [80, 29],
       [58, 50]])

- If i run the program again and again it will be generating new numbers everytime to fix to same values we use seed( )

In [21]:
rd.seed(2)
rd.randint(10,100,(3,2))

array([[50, 25],
       [82, 32],
       [53, 92]])

- rand( ) method generates only positive floating numbers between 0 and 1

In [22]:
# rd.seed(2)
rd.rand(3)

array([0.4847491 , 0.32053644, 0.15442667])

In [23]:
rd.rand(2,3)

array([[0.69886269, 0.11995054, 0.48517591],
       [0.63273773, 0.81822672, 0.68302599]])

- randn( ) will generate a random floating numbers between -1 - to - 1 which includes both postive as well as negative value  

In [24]:
rd.randn(2)

array([ 2.6460672 , -0.04386375])

In [25]:
r=rd.randn(2)
print(r)

print(np.mean(r))
print(np.std(r))

[-0.96561968  0.87866389]
-0.043477893335336915
0.9221417825159417


In [26]:
r=rd.randn(2,3)
print(r)

print(np.mean(r))
print(np.std(r))

[[-2.24587483  1.11957525 -1.054368  ]
 [-1.0088915  -0.06752199 -0.08142505]]
-0.5564176879218524
1.0472616542300617


- choice method will randomly select any one number from the given values

In [27]:
l=[10,20,30,40,50]
rd.choice(l)

50

In [28]:
l=[10,20,30,40,50]
rd.choice(l,3, replace=False)

array([20, 40, 10])

In [29]:
# l=[10,20,30,40,50]
# rd.choice(l,(2,3),replace=False) 
# ValueError: Cannot take a larger sample than population when 'replace=False'

In [30]:
l=[10,20,30,40,50]
rd.choice(l,(2,3))

array([[20, 10, 30],
       [30, 20, 10]])

In [31]:
col=['purple', 'red', 'yellow', 'maroon','pink', 'green', 'blue', 'white']

In [32]:
rd.choice(col)

'white'

In [33]:
rd.choice(col,3)

array(['red', 'blue', 'purple'], dtype='<U6')

In [34]:
rd.choice(col,3, replace=False)

array(['maroon', 'purple', 'white'], dtype='<U6')

In [35]:
rd.choice(col,3, replace=False, p=[0.13,0.1,0.12,0,0,0.11,0.5,0.04])

array(['white', 'blue', 'red'], dtype='<U6')